name: Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0 # Specify your .NET version

    # Install dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the project
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Run tests
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
